# Generated by Django 2.1.3 on 2018-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181111_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='所在机房'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='制造商'),
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
